name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache backend node_modules
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: backend-node-modules-${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            backend-node-modules-${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Install root dependencies
        run: npm ci

      - name: Install backend dependencies
        run: |
          if [ -f backend/package.json ]; then
            cd backend
            npm ci
            cd ..
          fi

      - name: Lint (root) - run only if lint:ci exists
        run: |
          # check for lint:ci, otherwise skip lint step
          if node -e "const p=require('./package.json'); process.exit(p.scripts && p.scripts['lint:ci'] ? 0 : 1)"; then
            echo "Found lint:ci script — running lint"
            npm run lint:ci
          else
            echo "lint:ci not defined — skipping lint step"
          fi

      - name: Run tests (root)
        run: |
          if npm run -s test --silent; then
            echo "Tests passed"
          else
            echo "No tests or tests failed"
            # fail the job if you want: exit 1
          fi

      - name: Build frontend
        run: |
          if npm run -s build --silent; then
            echo "Frontend build OK"
          else
            echo "No build script or frontend build failed"
            exit 1
          fi

      - name: Check dist exists
        id: check_dist
        run: |
          if [ -d "dist" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Build backend (optional)
        run: |
          if [ -f backend/package.json ]; then
            cd backend
            if npm run -s build --silent; then
              echo "Backend build OK"
            else
              echo "No backend build script or build failed - continuing"
            fi
          fi

      - name: Security audit (npm audit)
        run: npm audit --audit-level=moderate || true

      - name: Upload frontend-dist artifact (if present)
        if: steps.check_dist.outputs.exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist
